version: '3.7'

networks:
    codex-backend-full_default:
        external: true

services:
  api:
    build:
      context: .
      target: testing
    command: bash -c "python3 /daas/manage.py collectstatic --no-input && cd /daas/ && gunicorn daas.wsgi --timeout 300 -b 0.0.0.0:8001"
    volumes:
      - ./daas:/daas
      - /daas/daas_app/tests/resources/ # to not mount tests resources
      - ./static:/static
      - ./gunicorn_config/:/home/root/conf
    expose:
      - "8001"
      - "4567-4667"
    depends_on:
      - db
    tmpfs:
      - /tmpfs
    networks:
      - codex-backend-full_default
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "daas-api"

  redis:
    image: redis:7
    expose:
      - "6379"
    volumes:
      - ../redis-data:/data
    depends_on:
      - api
    networks:
      - codex-backend-full_default
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "redis"

  db:
    image: postgres:10.5
    expose:
      - "5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: daas
      POSTGRES_PASSWORD: iamaweakpassword
      POSTGRES_DB: daas
    networks:
      - codex-backend-full_default
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "daas-db"

  meta-extractor-worker:
    build:
      context: .
      dockerfile: metaExtractorWorkerDockerfile
    command: bash -c "rq worker --path / --url redis://redis:6379/0 unknown unknown_requeued --name agent_$$(hostname -I | cut -d' ' -f1)_$$(echo $$RANDOM)__$$(date +%s)"
    volumes:
      - ./meta_extractor:/daas
    links:
      - redis
    networks:
      - codex-backend-full_default
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "daas-meta-extractor-worker"

  pe-worker:
    build:
      context: .
      dockerfile: peWorkerDockerfile
    command: bash -c "rq worker --path / --url redis://redis:6379/0 pe_queue --name agent_$$(hostname -I | cut -d' ' -f1)_$$(echo $$RANDOM)__$$(date +%s)"
    volumes:
      - ./decompilers:/daas
      - ./utils/just_decompile:/just_decompile/
    tmpfs:
      - /tmpfs
    links:
      - redis
    networks:
      - codex-backend-full_default
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "daas-pe-worker"

  flash-worker:
    build:
      context: .
      dockerfile: flashWorkerDockerfile
    command: bash -c "rq worker --path / --url redis://redis:6379/0 flash_queue --name agent_$$(hostname -I | cut -d' ' -f1)_$$(echo $$RANDOM)__$$(date +%s)"
    volumes:
      - ./decompilers:/daas
    tmpfs:
      - /tmpfs
    links:
      - redis
    networks:
      - codex-backend-full_default
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "daas-flash-worker"

  java-worker:
    build:
      context: .
      dockerfile: javaWorkerDockerfile
    command: bash -c "rq worker --path / --url redis://redis:6379/0 java_queue --name agent_$$(hostname -I | cut -d' ' -f1)_$$(echo $$RANDOM)__$$(date +%s)"
    volumes:
      - ./decompilers:/daas
    tmpfs:
      - /tmpfs
    links:
      - redis
    networks:
      - codex-backend-full_default
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "daas-java-worker"

  apk-worker:
    build:
      context: .
      dockerfile: apkWorkerDockerfile
    command: bash -c "rq worker --path / --url redis://redis:6379/0 apk_queue --name agent_$$(hostname -I | cut -d' ' -f1)_$$(echo $$RANDOM)__$$(date +%s)"
    volumes:
      - ./decompilers:/daas
    tmpfs:
      - /tmpfs
    links:
      - redis
    networks:
      - codex-backend-full_default
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "daas-apk-worker"

  nginx:
    image: nginx:1.15.8
    volumes:
      - ./nginx_config:/etc/nginx/conf.d
      - ./certificates/etc_ssl_certs:/etc/ssl/certs
      - ./certificates/etc_ssl_private:/etc/ssl/private
      - ./nginx_snippets:/etc/nginx/snippets
      - ./daas/static:/static_files
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - codex-backend-full_default
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "daas-nginx"

  seaweedfs-master:
    build:
      context: .
      dockerfile: seaweedfsDockerfile
    command: ./seaweed master -ip=seaweedfs-master
    ports:
      - "9333:9333"
    expose:
      - "19333"
    networks:
      - codex-backend-full_default
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "daas-seaweedfs-master"

  seaweedfs-volume:
    build:
      context: .
      dockerfile: seaweedfsDockerfile
    command: ./seaweed volume -dir=/volume_data -max=1 -mserver=seaweedfs-master:9333 -port=8080 -ip=seaweedfs-volume
    volumes:
       - ../seaweedfs-data:/data
    links:
      - seaweedfs-master
    ports:
      - "8080:8080"
    expose:
      - "18080"
    networks:
      - codex-backend-full_default
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "daas-seaweedfs-volume"

  seaweedfs-filer:
    build:
      context: .
      dockerfile: seaweedfsDockerfile
    command: ./seaweed filer -master=seaweedfs-master:9333 -port=8888 -ip=seaweedfs-filer
    volumes:
      - ./seaweedfs:/etc/seaweedfs/
    expose:
      - "8888"
      - "18888"
    networks:
      - codex-backend-full_default
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "daas-seaweedfs-filer"
