version: '3.7'
services:
  api:
    image: metalion25/daas_api
    command: bash -c "python3 /daas/manage.py collectstatic --no-input && cd /daas/ && gunicorn daas.wsgi --timeout 300 -b 0.0.0.0:8001"
    volumes:
      - ./daas:/daas
      - /daas/daas_app/tests/resources/ # to not mount tests resources
      - ./static:/static
      - ./gunicorn_config/:/home/root/conf
    expose:
      - "8001"
      - "4567"
      - "4667"
  
  db:
    image: postgres:10.5
    expose:
      - "5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: daas
      POSTGRES_PASSWORD: iamaweakpassword
      POSTGRES_DB: daas

  mongo:
    image: mongo:8
    expose:
      - "27017"
    volumes:
      - ../mongo-data:/data/db
  
  nginx:
    image: nginx:1.15.8
    volumes:
      - ./nginx_config:/etc/nginx/conf.d
      - ./certificates/etc_ssl_certs:/etc/ssl/certs
      - ./certificates/etc_ssl_private:/etc/ssl/private
      - ./nginx_snippets:/etc/nginx/snippets
      - ./daas/static:/static_files
    ports:
      - "80:80"
      - "443:443"

  meta-extractor-worker:
    image: metalion25/daas_meta_extractor_worker
    command: bash -c "rq worker --path / --url redis://redis:6379/0 unknown unknown_requeued --name agent_$$(hostname -I | cut -d' ' -f1)_$$(echo $$RANDOM)__$$(date +%s)"
    volumes:
      - ./meta_extractor:/daas
  
  java-worker:
    image: metalion25/daas_java_worker
    command: bash -c "rq worker --path / --url redis://redis:6379/0 java_queue --name agent_$$(hostname -I | cut -d' ' -f1)_$$(echo $$RANDOM)__$$(date +%s)"
    volumes:
      - ./decompilers:/daas
    tmpfs:
      - /tmpfs
  
  pe-worker:
    image: metalion25/daas_pe_worker
    command: bash -c "rq worker --path / --url redis://redis:6379/0 pe_queue --name agent_$$(hostname -I | cut -d' ' -f1)_$$(echo $$RANDOM)__$$(date +%s)"
    volumes:
      - ./decompilers:/daas
      - ./utils/just_decompile:/just_decompile/
    tmpfs:
      - /tmpfs
  
  flash-worker:
    image: metalion25/daas_flash_worker
    command: bash -c "rq worker --path / --url redis://redis:6379/0 flash_queue --name agent_$$(hostname -I | cut -d' ' -f1)_$$(echo $$RANDOM)__$$(date +%s)"
    volumes:
      - ./decompilers:/daas
    tmpfs:
      - /tmpfs
  
  redis:
    image: redis:7
    expose:
      - "6379"
  
