# Generated by Django 2.2.10 on 2024-06-10 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=32, unique=True)),
                ('sha1', models.CharField(db_index=True, max_length=40)),
                ('sha2', models.CharField(max_length=64, unique=True)),
                ('file_name', models.CharField(max_length=300)),
                ('_data', models.BinaryField(blank=True, default=None, null=True)),
                ('size', models.IntegerField()),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file_type', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('seaweedfs_file_id', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-id'],
                'permissions': (('download_sample_permission', 'Download Sample'), ('download_source_code_permission', 'Download Source Code'), ('upload_sample_permission', 'Upload Sample'), ('delete_sample_permission', 'Delete Sample')),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
                ('_status', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='daas_app.Sample')),
            ],
            options={
                'permissions': (('cancel_task_permission', 'Cancel Task'),),
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('elapsed_time', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('exit_status', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('status', models.PositiveSmallIntegerField(db_index=True)),
                ('output', models.CharField(max_length=10100)),
                ('seaweed_result_id', models.CharField(max_length=20)),
                ('decompiler', models.CharField(max_length=100)),
                ('processed_on', models.DateTimeField(auto_now_add=True)),
                ('version', models.SmallIntegerField(default=0)),
                ('extension', models.CharField(max_length=15)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daas_app.Sample')),
            ],
            options={
                'permissions': (('update_statistics_permission', 'Update Statistics'),),
            },
        ),
    ]
