# Generated by Django 2.0.6 on 2018-09-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=100, unique=True)),
                ('sha1', models.CharField(max_length=100, unique=True)),
                ('sha2', models.CharField(max_length=100, unique=True)),
                ('data', models.BinaryField()),
                ('zip_result', models.BinaryField(default=None)),
                ('command_output', models.CharField(default=None, max_length=65000)),
            ],
            options={
                'ordering': ['sha1'],
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout', models.FloatField()),
                ('elapsed_time', models.FloatField()),
                ('exit_status', models.IntegerField()),
                ('timed_out', models.BooleanField()),
                ('exception_info', models.CharField(max_length=500)),
                ('output', models.CharField(max_length=65000)),
                ('errors', models.CharField(max_length=65000)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='statistics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daas_app.Statistics'),
        ),
    ]
