# Generated by Django 2.2.10 on 2025-02-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daas_app.Sample'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daas_app.Sample'),
        ),
    ]
