# Generated by Django 2.0.6 on 2018-09-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='exception_info',
        ),
    ]
