# Generated by Django 5.2 on 2025-04-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daas_app', '0002_auto_20250210_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='_data',
        ),
    ]
