# Generated by Django 2.0.6 on 2018-09-24 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daas_app', '0003_auto_20180924_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='command_output',
            field=models.CharField(blank=True, default=None, max_length=65000),
        ),
        migrations.AlterField(
            model_name='sample',
            name='statistics',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='daas_app.Statistics'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='zip_result',
            field=models.BinaryField(blank=True, default=None),
        ),
    ]
