# Generated by Django 5.2.3 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daas_app', '0004_alter_result_seaweed_result_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='seaweedfs_file_id',
            new_name='storage_file_id',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='seaweed_result_id',
            new_name='result_storage_id',
        ),
        migrations.AlterField(
            model_name='sample',
            name='storage_file_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_storage_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
