version: 2.1
orbs:
  docker: circleci/docker@0.5
jobs:
  build:
    resource_class: large
    machine: true
    working_directory: ~/daas
    steps:
      - checkout
      - docker/install-docker
      - docker/install-docker-compose:
          version: '1.25.1'
      - run: docker --version
      - run: docker-compose --version
      - run: docker-compose up -d syslog db
      - run:
          name: Build API
          command: docker-compose build api
      - run:
          name: Build C# worker
          command: docker-compose build pe_worker
          no_output_timeout: 10m
      - run:
          name: Build Flash worker
          command: docker-compose build flash_worker
      - run:
          name: Build Java worker
          command: docker-compose build java_worker
      - run:
          command: docker-compose up -d
      - run: sleep 10 && free -h && docker-compose ps
      - run:
          name: check containers. If at least one is down, print logs
          command: |
            if [ $(docker-compose  ps | grep exit | wc -l) -ne "0" ]; then
               docker-compose exec syslog cat /var/log/messages;
            fi
      - run: docker-compose exec syslog cat /var/log/messages
      - run: docker-compose exec api sh -c "pip freeze"
      - run: docker-compose exec api sh -c "apt list --installed"
      - run: docker-compose exec api sh -c "python /daas/manage.py makemigrations daas_app"
      - run: docker-compose exec api sh -c "python /daas/manage.py migrate"
      - run:
          name: executing api tests
          command: docker-compose exec api sh -c "coverage run --source='/daas/daas_app' /daas/manage.py test daas_app.tests.unit_tests -v 1 --force-color --exclude stress_test_csharp --noinput"
      - run:
          name: executing api tests in reverse order
          command: docker-compose exec api sh -c "python /daas/manage.py test daas_app.tests.unit_tests --reverse -v 1 --force-color --exclude stress_test_csharp --noinput"
      - run:
          name: print logs on fail after api tests
          command: docker-compose exec syslog cat /var/log/messages
          when: on_fail
      - run:
          name: executing metadata extractor tests
          command: docker-compose exec meta_extractor_worker sh -c "pip install pytest==5.2.1 pytest-cov==2.8.1 && pytest --cov-report term-missing --cov-config=/daas/.covconf --cov=daas /daas/tests/ --cov-fail-under=75"
      - run:
          name: executing decompilers tests
          command: docker-compose exec pe_worker sh -c "pip install pytest==5.2.1 pytest-cov==2.8.1 && pytest --cov-report term-missing --cov-config=/daas/.covconf --cov=daas /daas/tests/ --cov-fail-under=45"
      - run:
          name: print logs on fail after decompilers tests
          command: docker-compose exec syslog cat /var/log/messages
          when: on_fail
      - run:
          name: executing stress tests
          no_output_timeout: 60m
          command: |
            if [[ ! -z $CI_PULL_REQUEST ]]; then
               docker-compose exec api sh -c "python /daas/manage.py test daas_app.tests.decompilation_ratio_tests -v 1 --force-color --noinput ";
            fi
      - run:
          name: print logs on fail after stress tests
          command: docker-compose exec syslog cat /var/log/messages
          when: on_fail
      - run:
          name: executing coverage
          command: docker-compose exec api sh -c "coverage report -m --fail-under=70 --omit='*daas_app/tests/*,*daas_app/migrations/*,*daas_app/decompilers*'"
